name: radio_online
description: "Radio App"
publish_to: 'none'
version: 2.2.2+12

# Release Version: 2.2.2 (do not remove or edit this)
environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  just_audio: 0.9.46
  just_audio_background: ^0.0.1-beta.17
  awesome_notifications: ^0.10.1
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  flex_color_scheme: ^8.2.0
  flutter_bloc: ^9.1.1
  flutter_widget_from_html: ^0.16.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  intl: any
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  audio_service: ^0.18.18
  audio_session: ^0.1.25
  package_info_plus: ^8.3.0
  connectivity_plus: ^6.1.4
  flutter_svg: ^2.1.0


dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  very_good_analysis: ^8.0.0

dependency_overrides:
  intl:

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/languages/
